

revertdeletemove() {
	svn revert .$1
	svn delete --force .$2
	svn move --parents .$1 .$2
}



revertdeletemove	/trunk/ontopia/doc/db2tm/devguide.xml	/trunk/ontopia-maven/ontopia-db2tm/src/docbook/db2tm/user-guide.xml
revertdeletemove	/trunk/ontopia/doc/engine/devguide.xml	/trunk/ontopia-maven/ontopia-core/src/docbook/engine/devguide.xml
revertdeletemove	/trunk/ontopia/doc/navigator/devguide.xml	/trunk/ontopia-maven/ontopia-navigator/src/docbook/navigator/navguide.xml
revertdeletemove	/trunk/ontopia/doc/ontopia/startup.xml	/trunk/ontopia-maven/ontopia-core/src/docbook/install.xml
revertdeletemove	/trunk/ontopia/doc/ontopia/whatsnew.xml	/trunk/ontopia-maven/ontopia-core/src/docbook/whatsnew.xml
revertdeletemove	/trunk/ontopia/doc/osl/schemaspec.xml	/trunk/ontopia-maven/ontopia-core/src/docbook/schema/spec.xml
revertdeletemove	/trunk/ontopia/doc/osl/tutorial.xml	/trunk/ontopia-maven/ontopia-core/src/docbook/schema/tutorial.xml
revertdeletemove	/trunk/ontopia/doc/rdbms/install.xml	/trunk/ontopia-maven/ontopia-core/src/docbook/rdbms/install.xml
revertdeletemove	/trunk/ontopia/doc/tolog/predicate-ref.xml	/trunk/ontopia-maven/ontopia-core/src/docbook/query/predicate-reference.xml
revertdeletemove	/trunk/ontopia/doc/tolog/tutorial.xml	/trunk/ontopia-maven/ontopia-core/src/docbook/query/tutorial.xml
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/content/ContentInputStream.java	/trunk/ontopia-maven/ontopia-contentstore/src/main/java/net/ontopia/infoset/content/ContentInputStream.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/content/ContentStoreServlet.java	/trunk/ontopia-maven/ontopia-contentstore/src/main/java/net/ontopia/infoset/content/ContentStoreServlet.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/content/ContentStoreUtils.java	/trunk/ontopia-maven/ontopia-contentstore/src/main/java/net/ontopia/infoset/content/ContentStoreUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/content/FileContentStore.java	/trunk/ontopia-maven/ontopia-contentstore/src/main/java/net/ontopia/infoset/content/FileContentStore.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/content/InMemoryContentStore.java	/trunk/ontopia-maven/ontopia-contentstore/src/main/java/net/ontopia/infoset/content/InMemoryContentStore.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/content/JDBCBinaryInputStream.java	/trunk/ontopia-maven/ontopia-contentstore/src/main/java/net/ontopia/infoset/content/JDBCBinaryInputStream.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/content/JDBCContentStore.java	/trunk/ontopia-maven/ontopia-contentstore/src/main/java/net/ontopia/infoset/content/JDBCContentStore.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/content/JDBCSequenceContentStore.java	/trunk/ontopia-maven/ontopia-contentstore/src/main/java/net/ontopia/infoset/content/JDBCSequenceContentStore.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/content/RepairKeyFile.java	/trunk/ontopia-maven/ontopia-contentstore/src/main/java/net/ontopia/infoset/content/RepairKeyFile.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/core/LocatorReaderFactoryIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/core/LocatorReaderFactoryIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/core/Locators.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/core/Locators.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/core/PreloaderIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/core/PreloaderIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/core/DocumentIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/core/DocumentIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/core/GenericDocument.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/core/GenericDocument.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/impl/lucene/LuceneDocument.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/impl/lucene/LuceneDocument.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/impl/lucene/LuceneIndexer.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/impl/lucene/LuceneIndexer.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/impl/rdbms/RDBMSDocument.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/impl/rdbms/RDBMSDocument.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/impl/rdbms/RDBMSSearcher.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/impl/rdbms/RDBMSSearcher.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/impl/rdbms/RDBMSSearchResult.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/impl/rdbms/RDBMSSearchResult.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/topicmaps/TopicMapDocument.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/topicmaps/TopicMapDocument.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/topicmaps/TopicMapIteratorGenerator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/topicmaps/TopicMapIteratorGenerator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/topicmaps/TopicMapSearchResult.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/topicmaps/TopicMapSearchResult.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/utils/DefaultIndexerManager.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/utils/DefaultIndexerManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/fulltext/utils/ThreadedIndexerManager.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/fulltext/utils/ThreadedIndexerManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/impl/basic/GenericLocator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/impl/basic/GenericLocator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/impl/basic/URIFragmentLocator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/impl/basic/URIFragmentLocator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/utils/DiskPreloader.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/utils/DiskPreloader.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/infoset/utils/URLLocatorReaderFactory.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/infoset/utils/URLLocatorReaderFactory.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/net/Base64Decoder.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/net/Base64Decoder.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/net/Base64Encoder.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/net/Base64Encoder.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/net/data/DataURLConnection.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/net/data/DataURLConnection.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/net/MD5.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/net/MD5.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/jdbcspy/SpyConnection.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/jdbcspy/SpyConnection.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/jdbcspy/SpyDriver.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/jdbcspy/SpyDriver.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/jdbcspy/SpyPreparedStatement.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/jdbcspy/SpyPreparedStatement.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/jdbcspy/SpyResultSet.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/jdbcspy/SpyResultSet.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/jdbcspy/SpyStatement.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/jdbcspy/SpyStatement.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/jdbcspy/SpyStats.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/jdbcspy/SpyStats.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/proxy/DBCPConnectionFactory.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/proxy/DBCPConnectionFactory.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/proxy/DefaultConnectionFactory.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/proxy/DefaultConnectionFactory.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/proxy/ObjectRelationalMapping.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/proxy/ObjectRelationalMapping.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/proxy/QueryDeclarations.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/proxy/QueryDeclarations.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/proxy/SQLTypes.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/proxy/SQLTypes.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/persistence/rdbms/DatabaseProjectReader.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/persistence/rdbms/DatabaseProjectReader.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/cmdlineutils/rdbms/TranslateSourceLocators.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/cmdlineutils/rdbms/TranslateSourceLocators.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/core/DataTypes.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/core/DataTypes.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/core/events/test/AssociationEventsTest.java	/trunk/ontopia-maven/ontopia-core/src/test/java/net/ontopia/topicmaps/core/events/AssociationEventsTest.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/core/events/test/EventManagerTests.java	/trunk/ontopia-maven/ontopia-core/src/test/java/net/ontopia/topicmaps/core/events/EventManagerTests.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/core/TopicIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/core/TopicIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/core/TopicMapFragmentWriterIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/core/TopicMapFragmentWriterIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/Changelog.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/Changelog.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/ChangelogReaderIF.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/ChangelogReaderIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/ChangelogReaderWrapper.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/ChangelogReaderWrapper.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/Context.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/Context.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/CSVImport.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/CSVImport.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/DataSourceIF.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/DataSourceIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/Execute.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/Execute.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/ExpressionVirtualColumn.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/ExpressionVirtualColumn.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/Functions.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/Functions.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/FunctionVirtualColumn.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/FunctionVirtualColumn.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/JDBCUtils.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/JDBCUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/Processor.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/Processor.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/Relation.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/Relation.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/RelationMapping.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/RelationMapping.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/StateMachine.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/StateMachine.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/test/ChangelogTestGenerator.java	/trunk/ontopia-maven/ontopia-db2tm/src/test/java/net/ontopia/topicmaps/db2tm/ChangelogTestCase.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/test/FunctionVirtualColumnTest.java	/trunk/ontopia-maven/ontopia-db2tm/src/test/java/net/ontopia/topicmaps/db2tm/FunctionVirtualColumnTest.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/TupleReaderIF.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/TupleReaderIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/db2tm/ValueIF.java	/trunk/ontopia-maven/ontopia-db2tm/src/main/java/net/ontopia/topicmaps/db2tm/ValueIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/AbstractOntopolyTopicMapSource.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/AbstractOntopolyTopicMapSource.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/AbstractOntopolyURLReference.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/AbstractOntopolyURLReference.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/AbstractTopicMapReference.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/AbstractTopicMapReference.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/DefaultTopicMapReference.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/DefaultTopicMapReference.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/DefaultTopicMapSource.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/DefaultTopicMapSource.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/ReferenceNotOpenException.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/ReferenceNotOpenException.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/ResourceTopicMapSource.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/ResourceTopicMapSource.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/SharedStoreRegistry.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/SharedStoreRegistry.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/StoreFactoryReference.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/StoreFactoryReference.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/StoreRegistry.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/StoreRegistry.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/TopicMapReferenceIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/TopicMapReferenceIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/TopicMapRepositoryIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/TopicMapRepositoryIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/TopicMaps.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/TopicMaps.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/TopicMapSourceIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/TopicMapSourceIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/TopicMapSourceManager.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/TopicMapSourceManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/URLTopicMapSource.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/URLTopicMapSource.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/UserStoreRegistry.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/UserStoreRegistry.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/entry/XMLConfigSource.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/entry/XMLConfigSource.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/basic/InMemoryTopicMapStore.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/basic/InMemoryTopicMapStore.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/basic/InMemoryTopicMapTransaction.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/basic/InMemoryTopicMapTransaction.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/basic/SubjectIdentityCache.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/basic/SubjectIdentityCache.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/basic/Topic.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/basic/Topic.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/basic/TopicEvents.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/basic/TopicEvents.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/basic/TopicMap.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/basic/TopicMap.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/basic/TopicMapBuilder.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/basic/TopicMapBuilder.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/rdbms/Association.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/rdbms/Association.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/rdbms/config/schema.xml	/trunk/ontopia-maven/ontopia-core/src/main/resources/net/ontopia/topicmaps/impl/rdbms/config/schema.xml
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/rdbms/RDBMSSingleTopicMapSource.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/rdbms/RDBMSSingleTopicMapSource.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/rdbms/RDBMSTopicMapReference.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/rdbms/RDBMSTopicMapReference.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/rdbms/RDBMSTopicMapStore.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/rdbms/RDBMSTopicMapStore.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/rdbms/RDBMSTopicMapTransaction.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/rdbms/RDBMSTopicMapTransaction.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/rdbms/ReadOnlyAssociation.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/rdbms/ReadOnlyAssociation.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/rdbms/TopicMapBuilder.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/rdbms/TopicMapBuilder.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/AbstractAttachManager.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/AbstractAttachManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/AbstractTopicMapReader.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/AbstractTopicMapReader.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/AbstractTopicMapStore.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/AbstractTopicMapStore.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/AbstractTopicMapTransaction.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/AbstractTopicMapTransaction.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/Argument.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/Argument.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/ArgumentValidator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/ArgumentValidator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/AttachManager.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/AttachManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/BasicIndex.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/BasicIndex.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/DeletionUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/DeletionUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/FulltextIndexManager.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/FulltextIndexManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/IndexManagerIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/IndexManagerIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/LocatorInterningTable.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/LocatorInterningTable.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/ObjectTreeManager.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/ObjectTreeManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/PhantomAssociation.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/PhantomAssociation.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/ReificationUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/ReificationUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/StatisticsIndex.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/StatisticsIndex.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/StorePoolableObjectFactory.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/StorePoolableObjectFactory.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/TMRevitalizableIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/TMRevitalizableIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/TMRevitalizer.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/TMRevitalizer.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/TMRevitalizerIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/TMRevitalizerIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/TopicMapTransactionIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/TopicMapTransactionIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/impl/utils/TopicModificationManager.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/impl/utils/TopicModificationManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/impl/basic/ContextManager.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/impl/basic/ContextManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/plugins/PluginContentHandler.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/plugins/PluginContentHandler.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/portlets/pojos/RelatedTopics.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/portlets/pojos/RelatedTopics.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/portlets/pojos/SimilarTopics.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/portlets/pojos/SimilarTopics.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/portlets/pojos/YahooTree.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/portlets/pojos/YahooTree.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/taglibs/logic/ContextTag.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/taglibs/logic/ContextTag.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/taglibs/logic/ForEachTag.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/taglibs/logic/ForEachTag.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/taglibs/tolog/BaseOutputProducingTag.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/taglibs/tolog/BaseOutputProducingTag.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/taglibs/tolog/ContextManagerMapWrapper.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/taglibs/tolog/ContextManagerMapWrapper.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/utils/FrameworkUtils.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/utils/FrameworkUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/nav2/utils/NavigatorConfigFactory.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/topicmaps/nav2/utils/NavigatorConfigFactory.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/core/QueryProcessorFactoryIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/core/QueryProcessorFactoryIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/impl/basic/DynamicAssociationPredicate.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/impl/basic/DynamicAssociationPredicate.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/impl/basic/JavaModule.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/impl/basic/JavaModule.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/impl/basic/QueryMatches.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/impl/basic/QueryMatches.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/impl/basic/ReifiesPredicate.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/impl/basic/ReifiesPredicate.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/impl/basic/RulePredicate.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/impl/basic/RulePredicate.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/impl/basic/ValueLikePredicate.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/impl/basic/ValueLikePredicate.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/impl/utils/PredicateDrivenCostEstimator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/impl/utils/PredicateDrivenCostEstimator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/impl/utils/QueryOptimizer.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/impl/utils/QueryOptimizer.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/impl/utils/TologQueryProcessorFactory.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/impl/utils/TologQueryProcessorFactory.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/parser/DeleteStatement.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/parser/DeleteStatement.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/parser/GlobalParseContext.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/parser/GlobalParseContext.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/parser/InsertStatement.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/parser/InsertStatement.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/parser/LocalParseContext.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/parser/LocalParseContext.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/parser/ParseContextIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/parser/ParseContextIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/parser/TologParser.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/parser/TologParser.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/parser/TologQuery.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/parser/TologQuery.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/spi/LuceneSearcher.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/spi/LuceneSearcher.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/utils/QueryUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/utils/QueryUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/query/utils/QueryWrapper.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/query/utils/QueryWrapper.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/AssociationWalker.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/AssociationWalker.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/CopyUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/CopyUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/ctm/CTMEncodingSniffer.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/ctm/CTMEncodingSniffer.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/ctm/CTMTopicMapReader.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/ctm/CTMTopicMapReader.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/ctm/GlobalParseContext.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/ctm/GlobalParseContext.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/ctm/ParseContextIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/ctm/ParseContextIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/IdentityUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/IdentityUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/jtm/JTMTopicMapReader.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/jtm/JTMTopicMapReader.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/KeyGenerator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/KeyGenerator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/ltm/LTMTopicMapReader.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/ltm/LTMTopicMapReader.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/MergeUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/MergeUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/rdf/RDFFragmentExporter.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/rdf/RDFFragmentExporter.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/rdf/RDFIntroSpector.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/rdf/RDFIntroSpector.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/rdf/RDFTopicMapReader.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/rdf/RDFTopicMapReader.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/rdf/RDFToTopicMapConverter.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/rdf/RDFToTopicMapConverter.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/rdf/RDFUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/rdf/RDFUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/SameStoreFactory.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/SameStoreFactory.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/TypeHierarchyUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/TypeHierarchyUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/utils/xfml/XFMLTopicMapReader.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/utils/xfml/XFMLTopicMapReader.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/viz/VizConfigurationManager.java	/trunk/ontopia-maven/ontopia-vizigator/src/main/java/net/ontopia/topicmaps/viz/VizConfigurationManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/webed/impl/utils/ActionConfigContentHandler.java	/trunk/ontopia-maven/ontopia-webed/src/main/java/net/ontopia/topicmaps/webed/impl/utils/ActionConfigContentHandler.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/xml/CanonicalTopicMapWriter.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/xml/CanonicalTopicMapWriter.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/xml/CanonicalXTMWriter.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/xml/CanonicalXTMWriter.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/xml/XTM2TopicMapExporter.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/xml/XTM2TopicMapExporter.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/xml/XTMFragmentExporter.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/xml/XTMFragmentExporter.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/xml/XTMPathTopicMapSource.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/xml/XTMPathTopicMapSource.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/topicmaps/xml/XTMTopicMapFragmentWriter.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/topicmaps/xml/XTMTopicMapFragmentWriter.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/AndDecider.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/AndDecider.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/ArrayUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/ArrayUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CachedDecider.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CachedDecider.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CachedGrabber.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CachedGrabber.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CachedIndex.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CachedIndex.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CachedStringifier.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CachedStringifier.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CacheManager.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CacheManager.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/ChainedIndex.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/ChainedIndex.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CharacterSet.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CharacterSet.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CmdlineOptions.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CmdlineOptions.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CmdlineUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CmdlineUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CollectionCollection.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CollectionCollection.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CollectionFactory.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CollectionFactory.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CollectionMap.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CollectionMap.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CollectionSortedMap.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CollectionSortedMap.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CollectionStringifier.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CollectionStringifier.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CollectionUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CollectionUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CompactHashMap.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CompactHashMap.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CompactHashSet.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CompactHashSet.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/CompactIdentityHashSet.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/CompactIdentityHashSet.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/ContainmentDecider.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/ContainmentDecider.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/DebugUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/DebugUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/DeciderFilter.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/DeciderFilter.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/DeciderIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/DeciderIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/DeciderIterator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/DeciderIterator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/DeciderUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/DeciderUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/EmptyEnumerator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/EmptyEnumerator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/EncryptedInputStream.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/EncryptedInputStream.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/EncryptedOutputStream.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/EncryptedOutputStream.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/EncryptionUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/EncryptionUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/EnumerationIterator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/EnumerationIterator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/EqualsDecider.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/EqualsDecider.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/FilterIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/FilterIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/GrabberCollection.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/GrabberCollection.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/GrabberComparator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/GrabberComparator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/GrabberDecider.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/GrabberDecider.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/GrabberGrabber.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/GrabberGrabber.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/GrabberIF.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/GrabberIF.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/GrabberIterator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/GrabberIterator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/GrabberMap.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/GrabberMap.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/GrabberStringifier.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/GrabberStringifier.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/HashMapIndex.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/HashMapIndex.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/HistoryMap.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/HistoryMap.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/IteratorCollection.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/IteratorCollection.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/IteratorComparator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/IteratorComparator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/IteratorIterator.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/IteratorIterator.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/ObjectUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/ObjectUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/ontojsp/TaglibTagFactory.java	/trunk/ontopia-maven/ontopia-navigator/src/main/java/net/ontopia/utils/ontojsp/TaglibTagFactory.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/PropertyUtils.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/PropertyUtils.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/SoftHashMapIndex.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/utils/SoftHashMapIndex.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/utils/test/CompactHashMapTest.java	/trunk/ontopia-maven/ontopia-core/src/test/java/net/ontopia/utils/CompactHashMapTest.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/xml/DefaultXMLReaderFactory.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/xml/DefaultXMLReaderFactory.java
revertdeletemove	/trunk/ontopia/src/java/net/ontopia/xml/PrettyPrinter.java	/trunk/ontopia-maven/ontopia-core/src/main/java/net/ontopia/xml/PrettyPrinter.java
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/ACTIVITYLOG-after.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/ACTIVITYLOG-after.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/ACTIVITYLOG-before.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/ACTIVITYLOG-before.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/ACTIVITYLOG-changelog.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/ACTIVITYLOG-changelog.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/ACTIVITYLOG.ltm	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/ACTIVITYLOG.ltm
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/ACTIVITYLOG.xml	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/ACTIVITYLOG.xml
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/baseline/ACTIVITYLOG.cxtm	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/baseline/ACTIVITYLOG.cxtm
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/baseline/ONE2ONE.cxtm	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/baseline/ONE2ONE.cxtm
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/baseline/STATES.cxtm	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/baseline/STATES.cxtm
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/FIELDORDER-after.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/FIELDORDER-after.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/FIELDORDER-before.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/FIELDORDER-before.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/FIELDORDER-changelog.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/FIELDORDER-changelog.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/FIELDORDER.ltm	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/FIELDORDER.ltm
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/FIELDORDER.xml	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/FIELDORDER.xml
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/h2.properties	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/h2.properties
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/ONE2ONE-after.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/ONE2ONE-after.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/ONE2ONE-before.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/ONE2ONE-before.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/ONE2ONE-changelog.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/ONE2ONE-changelog.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/ONE2ONE.ltm	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/ONE2ONE.ltm
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/ONE2ONE.xml	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/ONE2ONE.xml
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/STATES-after.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/STATES-after.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/STATES-before.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/STATES-before.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/STATES-changelog.csv	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/STATES-changelog.csv
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/STATES.ltm	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/STATES.ltm
revertdeletemove	/trunk/ontopia/src/test-data/db2tm/in/sync/STATES.xml	/trunk/ontopia-maven/ontopia-db2tm/src/test/resources/net/ontopia/testdata/db2tm/in/sync/STATES.xml
revertdeletemove	/trunk/ontopia/src/test-data/ltm/baseline/dispname-merge-2.ltm	/trunk/ontopia-maven/ontopia-core/src/test/resources/net/ontopia/testdata/ltm/baseline/dispname-merge-2.ltm
revertdeletemove	/trunk/ontopia/src/test-data/ltm/in/dispname-merge-2.ltm	/trunk/ontopia-maven/ontopia-core/src/test/resources/net/ontopia/testdata/ltm/in/dispname-merge-2.ltm
revertdeletemove	/trunk/ontopia/src/test-data/query/issue-277.ltm	/trunk/ontopia-maven/ontopia-core/src/test/resources/net/ontopia/testdata/query/issue-277.ltm
revertdeletemove	/trunk/ontopia/src/test-data/rdf/baseline/two-subj-locators.rdf	/trunk/ontopia-maven/ontopia-core/src/test/resources/net/ontopia/testdata/rdf/baseline/two-subj-locators.rdf
revertdeletemove	/trunk/ontopia/src/test-data/rdf/err/two-subj-locators.rdf	/trunk/ontopia-maven/ontopia-core/src/test/resources/net/ontopia/testdata/rdf/err/two-subj-locators.rdf
revertdeletemove	/trunk/ontopia/src/test-data/rdf/in/two-subj-locators.rdf	/trunk/ontopia-maven/ontopia-core/src/test/resources/net/ontopia/testdata/rdf/in/two-subj-locators.rdf
revertdeletemove	/trunk/ontopia/src/test-data/tm2rdf/baseline/topic-with-typed-name.ctm	/trunk/ontopia-maven/ontopia-core/src/test/resources/net/ontopia/testdata/tm2rdf/baseline/topic-with-typed-name.ctm
revertdeletemove	/trunk/ontopia/src/test-data/tm2rdf/in/topic-with-typed-name.ctm	/trunk/ontopia-maven/ontopia-core/src/test/resources/net/ontopia/testdata/tm2rdf/in/topic-with-typed-name.ctm
revertdeletemove	/trunk/ontopia/src/test-data/various/alumni.xtm	/trunk/ontopia-maven/ontopia-core/src/test/resources/net/ontopia/testdata/various/alumni.xtm
revertdeletemove	/trunk/ontopia/src/webapps/manage/fragments/tagline-footer.jsp	/trunk/ontopia-maven/webapp-manage/src/main/webapp/fragments/tagline-footer.jsp
revertdeletemove	/trunk/ontopia/src/webapps/manage/views/template-one-column.jsp	/trunk/ontopia-maven/webapp-manage/src/main/webapp/views/template-one-column.jsp
revertdeletemove	/trunk/ontopia/src/webapps/manage/views/template-one-column1.jsp	/trunk/ontopia-maven/webapp-manage/src/main/webapp/views/template-one-column1.jsp
revertdeletemove	/trunk/ontopia/src/webapps/manage/views/template_no_frames.jsp	/trunk/ontopia-maven/webapp-manage/src/main/webapp/views/template_no_frames.jsp
revertdeletemove	/trunk/ontopia/src/webapps/omnigator/fragments/tagline-footer.jsp	/trunk/ontopia-maven/webapp-omnigator/src/main/webapp/fragments/tagline-footer.jsp
revertdeletemove	/trunk/ontopia/src/webapps/omnigator/models/index.jsp	/trunk/ontopia-maven/webapp-omnigator/src/main/webapp/models/index.jsp
revertdeletemove	/trunk/ontopia/src/webapps/omnigator/out-of-memory.jsp	/trunk/ontopia-maven/webapp-omnigator/src/main/webapp/out-of-memory.jsp
revertdeletemove	/trunk/ontopia/src/webapps/omnigator/plugins/db2tm/db2tm.jsp	/trunk/ontopia-maven/webapp-omnigator/src/main/webapp/plugins/db2tm/db2tm.jsp
revertdeletemove	/trunk/ontopia/src/webapps/omnigator/plugins/db2tm/plugin.xml	/trunk/ontopia-maven/webapp-omnigator/src/main/webapp/plugins/db2tm/plugin.xml
revertdeletemove	/trunk/ontopia/src/webapps/omnigator/plugins/db2tm/run.jsp	/trunk/ontopia-maven/webapp-omnigator/src/main/webapp/plugins/db2tm/run.jsp
revertdeletemove	/trunk/ontopia/src/webapps/omnigator/plugins/plugins/plugins.jsp	/trunk/ontopia-maven/webapp-omnigator/src/main/webapp/plugins/plugins/plugins.jsp
revertdeletemove	/trunk/ontopia/src/webapps/omnigator/plugins/query/query.jsp	/trunk/ontopia-maven/webapp-omnigator/src/main/webapp/plugins/query/query.jsp
revertdeletemove	/trunk/ontopia/src/webapps/omnigator/views/template_no_frames.jsp	/trunk/ontopia-maven/webapp-omnigator/src/main/webapp/views/template_no_frames.jsp
revertdeletemove	/trunk/ontopia/src/webapps/toplevel/about.jsp	/trunk/ontopia-maven/webapp-root/src/main/webapp/about.jsp
revertdeletemove	/trunk/ontopia/src/webapps/toplevel/frontpage.css	/trunk/ontopia-maven/webapp-root/src/main/webapp/frontpage.css
revertdeletemove	/trunk/ontopia/src/webapps/toplevel/index.html	/trunk/ontopia-maven/webapp-root/src/main/webapp/index.html

# unset revertdeletemove

# patch changes to new files in trunk
patch -p0 -i merge-HEAD-patch.diff 

# add newly created files to svn
svn add trunk/ontopia-maven/ontopia-core/src/test/java/net/ontopia/topicmaps/impl/basic/events/AssociationEventsTest.java
svn add trunk/ontopia-maven/ontopia-core/src/test/java/net/ontopia/topicmaps/impl/basic/events/EventManagerTests.java
svn add trunk/ontopia-maven/ontopia-core/src/test/java/net/ontopia/topicmaps/impl/rdbms/events/AssociationEventsTest.java
svn add trunk/ontopia-maven/ontopia-core/src/test/java/net/ontopia/topicmaps/impl/rdbms/events/EventManagerTests.java
